entities:
  - Agreement: A formal peace agreement, accord, memorandum, protocol, or treaty.
  - Party: A state, government, armed group, movement, international org, or coalition that is a signatory or stakeholder.
  - Person: A named individual (negotiator, head of state, envoy, mediator, commander).
  - Organization: A non-state organization (IGO, NGO, regional bloc, mission, court).
  - Location: A place name (city, country, region) relevant to talks or implementation.
  - Date: A specific calendar date (ISO or natural-language) for signing, implementation, or deadlines.
  - Topic: A thematic area covered (ceasefire, DDR, power-sharing, elections, justice, security, humanitarian access).
  - Clause: A specific clause, article, annex, or section of an agreement text.
  - Provision: A concrete commitment or measure within a clause (e.g., prisoner release, cantonment).
  - Mechanism: A body or process created by the agreement (joint commission, verification mission, tribunal).
  - MonitoringBody: An actor tasked with verification or monitoring (UN mission, regional mission, third-party).
  - ImplementationStep: A discrete step or milestone required by the agreement.
  - Deadline: A time limit or target date for an implementation step.
  - Sanction: A sanction or penalty referenced (travel ban, asset freeze, arms embargo).
  - Territory: A geographic area subject to control, withdrawal, buffer, or demarcation.
  - Resource: A resource referenced (oil field, mine, customs revenue).
  - Instrument: A legal or policy instrument related to the agreement (UNSC resolution, law, decree).
  - Event: A related event (referendum, election, atrocity, ceasefire incident).

relationships:
  - SIGNED_BY: Agreement -> Party | Person | Organization
  - SIGNED_IN: Agreement -> Location
  - HAS_DATE: Agreement | Event | Deadline -> Date
  - ADDRESSES: Agreement -> Topic
  - INCLUDES_CLAUSE: Agreement -> Clause
  - SPECIFIES: Clause -> Provision
  - CREATES: Agreement -> Mechanism | MonitoringBody
  - MANDATES: Mechanism | MonitoringBody -> ImplementationStep | Provision
  - MONITORS: MonitoringBody -> ImplementationStep | Provision
  - IMPLEMENTS: Party | Mechanism -> ImplementationStep | Provision
  - OBLIGATES: Agreement | Clause -> Party
  - BENEFITS: Provision -> Party
  - GOVERNS_TERRITORY: Agreement | Clause -> Territory
  - AFFECTS_RESOURCE: Agreement | Provision -> Resource
  - REFERENCED_BY: Instrument -> Agreement | Clause
  - ENFORCES: Instrument | Sanction -> Party
  - IMPOSES_SANCTION: Agreement | Instrument -> Sanction
  - FACILITATED_BY: Agreement -> Person | Organization
  - PARTICIPATED_IN: Party | Person | Organization -> Event
  - RELATES_TO: Agreement | Clause | Provision -> Topic
